name: Style

on:
 push:
   branches:
     - main
     - 'version-**'
 pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-style:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"
        cache-dependency-path: |
          setup.py
          pyproject.toml
          style-requirements.txt

    - name: Install dependencies
      run: |
        pip install -r style-requirements.txt

    - name: Clang Format
      run: ./script/clang-format --check

    - name: CMake Format
      if: ${{ always() }}
      run: ./script/cmake-format --check

    - name: Run isort
      if: ${{ always() }}
      run: |
        isort --check script/ src/ tests/ test-data/

    - name: Lint with flake8
      if: ${{ always() }}
      run: |
        flake8

    - name: Run black
      if: ${{ always() }}
      uses: psf/black@stable

    - name: Run pylint
      run: |
        pip install .  # We need the dependencies of ERT to avoid import-error
        script/pylint
